# This is used in the "assess_fits" analyses to draw the plots showing
# improvement in the Poisson NMF fits over time; the plots are
# arranged using plot_grid from the cowplot package.
#  
# Input arguments "dat" and "fits" should be generated by the script
# compile_poisson_nmf_fits.R. It is assumed that Poisson NMF models
# were fit for k = 2-13, using three different algorithms (EM, CCD,
# SCD), and with and without extrapolation.
create_progress_plots <- function (dat, fits, y = c("loglik","res")) {

  # Process the input arguments.
  y <- match.arg(y)

  # This list will be used to store the plots for each choice of k,
  # for k=2-13. (The first list element is unused.)
  k            <- 13
  plots        <- vector("list",k)
  names(plots) <- paste0("k",1:k)
  
  # For each fit, change the timings from seconds (s) to hours (h).
  n           <- length(fits)
  names(fits) <- with(dat,paste0(method,ifelse(extrapolate,"+ex","")))
  for (i in 1:n) {
    fit                 <- fits[[i]]
    fit$progress$timing <- fit$progress$timing/3600
    fits[[i]]           <- fit
  }
   
  # Repeat for each choice of k, the number of topics. The legend is
  # only included in the k = 2 plot.
  clrs <- c("deepskyblue","darkorange","darkmagenta")
  for (i in 2:k) {
    rows <- which(dat$k == i)
    plots[[i]] <-
      suppressMessages(
        plot_progress_poisson_nmf(fits[rows],x = "timing",y = y,
                                  add.point.every = 150,shapes = 21,
                                  colors = rep(clrs,2),
                                  fills = c(clrs,rep("white",3))) +
        scale_y_continuous(trans = "log10",breaks = 10^seq(-8,8)) +
        labs(x = "runtime (h)",title = paste("K =",i)) +
        theme_cowplot(font_size = 10) +
        theme(plot.title = element_text(size = 10,face = "plain")))
    if (i == 2)
      plots[[i]] <- plots[[i]] +
        theme(legend.position = c(0.95,0.95),
              legend.justification = c("right","top"),
              legend.title = element_blank())
    else
      plots[[i]] <- plots[[i]] +
        guides(color = "none",fill = "none",size = "none",
               shape = "none",linetype = "none")
  }

  # Arrange the plots using plot_grid.
  return(do.call(plot_grid,plots[-1]))
}
