# This is used in the "assess_fits_purified_pbmc" analysis to draw the
# plots showing improvement in the fits over time; the plots are
# arranged using plot_grid from the cowplot package. To avoid showing
# the legend in every plot, a separate plot is created showing the
# legend only.
#  
# Input arguments "dat" and "fits" should be generated by
# compile_poisson_nmf_fits.R. It is assumed that Poisson NMF models
# were fit for k = 2-12, using three different algorithms (EM, CCD,
# SCD), and with and without extrapolation.
create_progress_plots <- function (dat, fits, y = c("loglik","res"),
                                   iterations = 1:1000) {

  # These are the colours that will be used to plot the results from
  # running the three methods: EM, CCD and SCD.
  clrs <- c("deepskyblue","darkorange","darkmagenta")
  
  # Process the input arguments.
  y <- match.arg(y)

  # This list will be used to store the plots for each choice of k,
  # for k=2-13.
  k            <- 13
  plots        <- vector("list",k)
  names(plots) <- paste0("k",1:k)

  # Repeat for each choice of k, the number of topics. The legend is
  # removed from all of these plots.
  for (i in 2:k) {
    rows       <- which(dat$k == i)
    plots[[i]] <- plot_progress_poisson_nmf(fits[rows]) +
      guides(color = "none",fill = "none",size = "none",shape = "none",
             linetype = "none") +
      theme_cowplot(10)
  }

  # Arrange the 12 plots in a 3 x 4 grid.
  return(do.call(plot_grid,plots[-1]))
}
