# Simulate gene expression data (UMI counts) under a "toy" expression
# model. Samples (cells) are drawn from a multinomial topic model in
# which topics are "gene programs". The input arguments specify the
# number of samples (n), the number of genes (m), the number of topics
# or "gene programs" (k), and the total expression of each sample (s),
# which specifies the "size" parameter in the call to rmultinom. The
# outputs are the n x m counts matrix (X), and the gene frequencies
# (F) and topic proportions (L) used to generate X.
simulate_toy_gene_data <- function (n, m, k, s) {

  # Generate the "gene programs"; that is, the m x k matrix of gene
  # frequencies, by drawing uniformly at random from
  # [0,1]. Each column is a "gene program".
  F <- matrix(runif(m*k),m,k)

  # Generate the topic proportions; that is, for each sample i =
  # 1,...,n, the proportion that each of the gene programs contributes
  # to that sample. For 90% of the samples, counts are generated
  # primarily by a single gene program; the remaining 10% of samples
  # are generated by sampling roughly equally from all three gene
  # programs.
  L <- matrix(0,n,k)
  for (i in 1:n) {
    if (runif(1) < 0.9) {
      x <- rep(0,k)
      x[sample(k,1)] <- 1
    } else
      x <- rep(1/k,k)
    x <- x + abs(rnorm(k,0,0.15))
    L[i,] <- x/sum(x)
  }

  # Simulate the n x m counts matrix from the multinomial topic model.
  X <- matrix(0,n,m)
  P <- tcrossprod(L,F)
  for (i in 1:n)
    X[i,] <- rmultinom(1,s,P[i,])

  # Add row and column names to the outputs.
  rownames(X) <- paste("s",1:n)
  rownames(L) <- paste("s",1:n)
  colnames(X) <- paste("g",1:m)
  rownames(F) <- paste("g",1:m)
  colnames(L) <- paste("k",1:k)
  colnames(F) <- paste("k",1:k)
  
  # Outputs the n x m counts matrix (X), and the gene frequencies
  # (F) and topic proportions (L) used to generate counts.
  return(list(X = X,F = F,L = L))
}

# Plot the topic proportions L on a ternary plot.
create_ternary_plot <- function (L) {
  L <- as.data.frame(L)
  TernaryPlot(alab = names(L)[1],blab = colnames(L)[2],clab = colnames(L)[2],
              grid.col = "skyblue",grid.minor.lines = 0)
  TernaryPoints(L,pch = 21,col = "white",bg = "black",cex = 0.8)
  return(invisible())
}

# Plot the 2-d embedding generated by t-SNE, and colour the points
# according to the topic with the largest contribution. This code
# assumes there are 3 topics, and L is the n x 3 matrix of topic
# proportions.
plot_tsne <- function (tsne, L) {
  colnames(tsne$Y) <- c("d1","d2")
  pdat <- cbind(tsne$Y,data.frame(k = factor(apply(L,1,which.max))))
  return(ggplot(pdat,aes(x = d1,y = d2,fill = k)) +
    geom_point(shape = 21,color = "white",size = 2,show.legend = FALSE) +
    scale_fill_manual(values = c("dodgerblue","darkorange","darkblue")) +
    labs(x = "tsne 1",y = "tsne 2") +
    theme_cowplot(font_size = 12))
}
