---
title: Analysis of single-cell RNA-seq data using topic models
author: Peter Carbonetto
site: workflowr::wflow_site
output: workflowr::wflow_html
---

Evaluation of DE analysis using a topic model
---------------------------------------------

In these pages, we assess the new topic-model-based methods for
differential expression analysis, and compare with MAST and DESeq2.

+ [Evaluation of DE methods using simulated data](de_analysis_detailed_look.html)

+ [Evaluation of DE analysis with more than two topics](de_analysis_detailed_look_more.html)

+ [Illustration in PBMC data](de_analysis_purified_pbmc.html)

+ For a more systematic evaluation in multiple simulated data sets,
  see these pages:

  - [Comparison of new DE analysis methods with MAST and DESeq2](de_analysis_mast_deseq2.html)

  - *Add another link here*

  - *Add yet another link here*

Data preparation
----------------

These pages detail the steps taken to prepare the single-cell RNA-seq
data sets for topic modeling analysis.

+ [PBMC](prepare_purified_pbmc.html)

+ [Droplet](prepare_droplet.html)

+ [Pulse-seq](prepare_pulseseq.html)

Assess Poisson NMF model fits
-----------------------------

In these pages, we compare the quality of the Poisson NMF fits with
different updates (EM, CCD, SCD, with and without extrapolation), and
with different settings for $K$.

+ [PBMC](assess_fits_purified_pbmc.html)

+ [Droplet](assess_fits_droplet.html)

+ [Pulse-seq](assess_fits_pulseseq.html)

Identify clusters
-----------------

In these pages, we identify clusters of cells from the mixture
proportions.

+ [PBMC](clusters_purified_pbmc.html)

+ [Droplet](clusters_droplet.html)

+ [Pulse-seq](clusters_pulseseq.html)

Visualize and annotate topics
-----------------------------

In these pages, we annotate topics and substructures to determine
their biological relevance. This includes differential expression
analysis using the topic model.

+ [Droplet and pulse-seq](plots_tracheal_epithelium.html)

Examine single-cell likelihoods
-------------------------------

In these pages, we calculate single-cell likelihoods to assess how
well the multinomial topic model captures expression in different
cells and cell types.

+ [PBMC](loglik_purified_pbmc.html)

+ [Droplet](loglik_droplet.html)

+ [Pulse-seq](loglik_pulseseq.html)

Other analyses
--------------

+ [PCA vs. t-SNE and UMAP: an illustration](pca_vs_tsne.html)
