library(Matrix)
library(MASS)
load("../data/pbmc_purified.RData")
i  <- which(samples$celltype == "CD19+ B")
j  <- which(samples$celltype != "CD19+ B")
f0 <- colMeans(counts[j,])
f1 <- colMeans(counts[i,])
e  <- 1e-15
lfc <- log2((f1 + e)/(f0 + e))
fit <- suppressWarnings(fitdistr(lfc[abs(lfc) < 10],"t"))
x <- -0.42 + 0.69 * rt(20000,df = 1.65)
hist(lfc[abs(lfc) < 5],n = 64)
hist(x[abs(x) < 5],n = 64)
