---
title: Visualize and interpret topics in pulse-seq data
author: Peter Carbonetto
output: workflowr::wflow_html
---

```{r knitr-opts, include=FALSE}
knitr::opts_chunk$set(comment = "#",collapse = TRUE,results = "hold",
                      fig.align = "center")
```

Load the packages used in the analysis below.

```{r load-pkgs}
library(Matrix)
library(fastTopics)
library(ggplot2)
library(cowplot)
```

Load the UMI count data.

```{r load-data}
load("../data/pulseseq.RData")
samples$tissue <- as.character(samples$tissue)
samples$tissue[samples$tissue == "club (hillock-associated)"] <- "club"
samples$tissue[samples$tissue == "goblet.1"] <- "goblet"
samples$tissue[samples$tissue == "goblet.2"] <- "goblet"
samples$tissue[samples$tissue == "goblet.progenitor"] <- "goblet"
samples$tissue[samples$tissue == "tuft.1"] <- "tuft"
samples$tissue[samples$tissue == "tuft.2"] <- "tuft"
samples$tissue[samples$tissue == "tuft.progenitor"] <- "tuft"
samples$tissue <- factor(samples$tissue)
```

Load the $k = 11$ Poisson NMF model fit:

```{r load-fit}
fit <- readRDS("../output/pulseseq/rds/fit-pulseseq-scd-ex-k=11.rds")$fit
```

Loadings plot:

```{r loading-plot}
p1 <- loadings_plot(poisson2multinom(fit),samples$tissue)
```

PCA plot:

```{r pca-plot}
fit2 <- poisson2multinom(fit)
pca  <- prcomp(fit2$L)
y    <- samples$tissue
clrs <- c("royalblue",      # basal
          "firebrick",      # ciliated
          "forestgreen",    # club
	      "gold",           # goblet
		  "darkmagenta",    # ionocyte
          "darkorange",     # neuroendocrine
		  "tomato",         # proliferating
		  "darkgray")       # tuft
levels(y) <- clrs
pdat <- cbind(samples,pca$x)
ggplot(pdat,aes(x = PC5,y = PC6,fill = tissue)) +
  geom_point(shape = 21,color = "white",size = 2) +
  scale_fill_manual(values = levels(y)) +
  theme_cowplot(font_size = 12)
y <- as.character(y)
plot(pca$x[,3],pca$x[,4],pch = 21,col = "white",bg = y,cex = 0.8)
plot(pca$x[,5],pca$x[,6],pch = 21,col = "white",bg = y,cex = 0.8)
```

t-SNE plot:

```{r tsne-plot}
library(Rtsne)
set.seed(1)
n    <- nrow(fit$L)
rows <- sample(n,7000)
tsne <- Rtsne(poisson2multinom(fit)$L[rows,],pca = FALSE,normalize = FALSE,
              theta = 0.1,max_iter = 1000,perplexity = 70,eta = 7000/12,
              num_threads = 4,verbose = TRUE)
colnames(tsne$Y) <- c("d1","d2")
p2 <- ggplot(cbind(samples[rows,],tsne$Y),aes(x = d1,y = d2,fill = tissue)) +
  geom_point(shape = 21,size = 1.5,color = "white") +
  scale_fill_manual(values = clrs) +
  theme_cowplot(font_size = 12)
```

Structure plot:

```{r structure-plot}
set.seed(1)
fit2 <- poisson2multinom(fit)
fit2$L <- fit2$L[samples$tissue == "ionocyte",]
p3 <- structure_plot(fit2,num_threads = 4,
                     perplexity = 30)
p3 <- structure_plot(poisson2multinom(fit),n = 2000,num_threads = 4,
                     perplexity = 100)
```

Differential count analysis:

```{r diff-count-analysis}
diff_count_res <- diff_count_analysis(fit,counts)
```

Volcano plots:

```{r volcano-plots}
p3 <- volcano_plot(diff_count_res,labels = genes$symbol,
                   label_above_quantile = 0.995)
```
