---
title: Visualize and interpret topics in droplet and pulse-seq data
author: Peter Carbonetto
output: workflowr::wflow_html
---

**TO DO:** Add introductory text here.

```{r knitr-opts, include=FALSE}
knitr::opts_chunk$set(comment = "#",collapse = TRUE,results = "hold",
                      fig.align = "center")
```

Load the packages used in the analysis below.

```{r load-pkgs, message=FALSE}
library(fastTopics)
library(ggplot2)
library(cowplot)
source("../code/plots.R")
```

Load the sample annotations (the count data are not needed at this
stage of the analysis).

```{r load-data}
load("../data/droplet.RData")
samples_droplet <- samples
load("../data/pulseseq.RData")
samples_pulseseq <- samples
rm(samples,counts)
```

Load the $k = 7$ Poisson NMF model fit:

```{r load-fits}
droplet_fit <- readRDS("../output/droplet/rds/fit-droplet-scd-ex-k=7.rds")$fit
pulseseq_fit <- readRDS("../output/pulseseq/rds/fit-pulseseq-scd-ex-k=11.rds")$fit
```

Rare and abundant cell types.

```{r droplet-plot}
probs <- c(0.1,0.25,0.5)
fit   <- poisson2multinom(droplet_fit)
k     <- ncol(fit$L)
m     <- length(probs)
out   <- apply(fit$L,2,function (x) rev(cumsum(rev(table(cut(x,c(probs,1)))))))
pdat  <- data.frame(k    = factor(rep(paste0("k",1:k),each = m),
                                  c("k2","k5","k4","k3","k6",""k7,"k1")),
                    prob = factor(rep(probs,times = k)),
					n    = as.vector(out))
ggplot(pdat,aes_string(x = "k",y = "n",fill = "prob")) +
  geom_col(color = "white",position = "dodge",width = 0.8) +
  scale_fill_manual(values = c("tomato","dodgerblue","darkblue")) +
  labs(x = "topic",y = "samples") +
  theme_cowplot(font_size = 12)
```

```{r pulseseq-plot}
```

```{r droplet-pca}
fit <- poisson2multinom(droplet_fit)
pca <- prcomp(fit$L)
ggplot(as.data.frame(pca$x),aes(x = PC1,y = PC2)) +
  geom_point(shape = 21,color = "white",fill = "black",size = 2) +
  theme_cowplot(font_size = 12)
ggplot(as.data.frame(pca$x),aes(x = PC5,y = PC6)) +
  geom_point(shape = 21,color = "white",fill = "black",size = 2) +
  theme_cowplot(font_size = 12)
```

```{r droplet-pca-with-topics}
ggplot(cbind(pca$x,data.frame(k2 = fit$L[,2])),
       aes(x = PC1,y = PC2,fill = k2)) +
  geom_point(shape = 21,color = "white",size = 2) +
  scale_fill_gradient2(low = "deepskyblue",mid = "gold",high = "orangered",
                       midpoint = 0.5) +
  theme_cowplot(font_size = 12)
ggplot(cbind(pca$x,data.frame(k5 = fit$L[,5])),
       aes(x = PC1,y = PC2,fill = k5)) +
  geom_point(shape = 21,color = "white",size = 2) +
  scale_fill_gradient2(low = "deepskyblue",mid = "gold",high = "orangered",
                       midpoint = 0.5) +
  theme_cowplot(font_size = 12)
ggplot(cbind(pca$x,data.frame(k6 = fit$L[,6])),
       aes(x = PC1,y = PC2,fill = k6)) +
  geom_point(shape = 21,color = "white",size = 2) +
  scale_fill_gradient2(low = "deepskyblue",mid = "gold",high = "orangered",
                       midpoint = 0.5) +
  theme_cowplot(font_size = 12)
ggplot(cbind(pca$x,data.frame(k1 = fit$L[,1])),
       aes(x = PC5,y = PC6,fill = k1)) +
  geom_point(shape = 21,color = "white",size = 2) +
  scale_fill_gradient2(low = "deepskyblue",mid = "gold",high = "orangered",
                       midpoint = 0.5) +
  theme_cowplot(font_size = 12)
```

```{r}
ggplot(cbind(pca$x,data.frame(k3 = fit$L[,3])),
       aes(x = PC1,y = PC2,fill = k3)) +
  geom_point(shape = 21,color = "white",size = 2) +
  scale_fill_gradient2(low = "deepskyblue",mid = "gold",high = "orangered",
                       midpoint = 0.5) +
  theme_cowplot(font_size = 12)
ggplot(cbind(pca$x,data.frame(k4 = fit$L[,4])),
       aes(x = PC1,y = PC2,fill = k4)) +
  geom_point(shape = 21,color = "white",size = 2) +
  scale_fill_gradient2(low = "deepskyblue",mid = "gold",high = "orangered",
                       midpoint = 0.5) +
  theme_cowplot(font_size = 12)
```
