Differential expression analysis
--------------------------------

B-cells
-------

*Add text here.*

NK cells
--------

*Add text here.*

```{r b-cells, eval=FALSE}
pdat <- data.frame(x     = diff_count_res_clusters$Z[,"B"],
                   y     = diff_count_res$Z[,"k3"],
                   label = genes$symbol,
				   stringsAsFactors = FALSE)
pdat[with(pdat,abs(x) < 150 & abs(y) < 150),"label"] <- ""
p10 <- ggplot(pdat,aes(x = x,y = y,label = label)) +
  geom_point(shape = 21,fill = "dodgerblue",color = "white") +
  geom_text_repel(color = "black",size = 2.25,fontface = "italic",
                  box.padding = 0.1,point.padding = 0.1,
                  segment.color = "black",segment.size = 0.25,
                  na.rm = TRUE) +
  geom_abline(slope = 1,intercept = 0,color = "lightskyblue",
              linetype = "dotted") + 
  theme_cowplot(font_size = 10)
print(p10)
```


```{r, eval=FALSE}
pdat <- data.frame(x     = diff_count_res_clusters$Z[,"C2"],
                   y     = diff_count_res$Z[,"k2"],
                   label = genes$symbol,
				   stringsAsFactors = FALSE)
pdat[with(pdat,abs(x) < 175 & abs(y) < 175),"label"] <- ""
p8 <- ggplot(pdat,aes(x = x,y = y,label = label)) +
  geom_point(shape = 21,fill = "dodgerblue",color = "white") +
  geom_text_repel(color = "black",size = 2.25,fontface = "italic",
                  box.padding = 0.1,point.padding = 0.1,
                  segment.color = "black",segment.size = 0.25,
                  na.rm = TRUE) +
  geom_abline(slope = 1,intercept = 0,color = "lightskyblue",
              linetype = "dotted") + 
  theme_cowplot(font_size = 10)
print(p8)
```

```{r cd14, eval=FALSE}
pdat <- data.frame(x     = diff_count_res_clusters$Z[,"C2"],
                   y     = diff_count_res$Z[,"k2"],
                   label = genes$symbol,
				   stringsAsFactors = FALSE)
pdat[with(pdat,abs(x) < 175 & abs(y) < 175),"label"] <- ""
p9 <- ggplot(pdat,aes(x = x,y = y,label = label)) +
  geom_point(shape = 21,fill = "dodgerblue",color = "white") +
  geom_text_repel(color = "black",size = 2.25,fontface = "italic",
                  box.padding = 0.1,point.padding = 0.1,
                  segment.color = "black",segment.size = 0.25,
                  na.rm = TRUE) +
  geom_abline(slope = 1,intercept = 0,color = "lightskyblue",
              linetype = "dotted") + 
  theme_cowplot(font_size = 10)
print(p9)
```

```{r nk-cells, eval=FALSE}
pdat <- data.frame(x     = diff_count_res_clusters$Z[,"A1"],
                   y     = diff_count_res$Z[,"k4"],
                   mean  = diff_count_res$colmeans,
                   label = genes$symbol,
				   stringsAsFactors = FALSE)
pdat[with(pdat,abs(x) < 150 & abs(y) < 150),"label"] <- ""
p11 <- ggplot(pdat,aes(x = x,y = y,fill = mean,label = label)) +
  geom_point(shape = 21,color = "white") +
  geom_text_repel(color = "black",size = 2.25,fontface = "italic",
                  box.padding = 0.1,point.padding = 0.1,
                  segment.color = "black",segment.size = 0.25,
                  na.rm = TRUE) +
  geom_abline(slope = 1,intercept = 0,color = "lightskyblue",
              linetype = "dotted") + 
  scale_fill_gradient2(low = "deepskyblue",mid = "gold",high = "orangered",
                       midpoint = 10) +
  theme_cowplot(font_size = 10)
print(p11)
```
