---
title: "Topics vs. clusters: an illustration"
author: Peter Carbonetto
output: workflowr::wflow_html
---

*Add introductory text here.*

```{r knitr-opts, include=FALSE}
knitr::opts_chunk$set(comment = "#",collapse = TRUE,results = "hold",
                      fig.align = "center")
```

Load packages used in the analysis below, as well as some functions
written for this analysis.

```{r load-pkgs, message=FALSE}
library(ggplot2)
library(cowplot)
library(Ternary)
library(fastTopics)
source("../code/functions_for_topics_vs_clusters.R")
```

Simulate a gene expression data set.

```{r simulate-data}
set.seed(1)
out <- simulate_toy_gene_data(n = 400,m = 40,k = 3,s = 1000)
X   <- out$X
```

Fit a multinomial topic model to these data.

```{r fit-multinom-topic-model}
fit <- fit_poisson_nmf(X,k = 3,numiter = 100,verbose = FALSE,
                       control = list(extrapolate = TRUE))
fit <- poisson2multinom(fit)
```

Plot the estimated topic proportions.

```{r plot-topic-proportions, fig.height=4, fig.width=4}
par(mar = c(0,0,0,0))
create_ternary_plot(fit$L)
```
